version: '3'

services:
  api:
  #Image instead of build since in prod, you want to pull a working image as opposed to experminemnting
    image: tumitarantino/fastapi-tutorial
    #HOST:CONTAINER, 8000 (my laptop,e.gd)  →  8000 (inside Docker container)
    ports:
      - "80:8000"
      #I think this is fine, but this assumes these are what the variables will be called in prod which is a big ask
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    #command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    #Added to fix race condition
    depends_on:
      postgres:
        condition: service_healthy
    #depends_on:
     # - postgres

  #Uses Dns somehow? postgres ip, docker internal network?
  postgres:
  #Doesn't need dockerfile, it is from the sky, like dockerhub, it is already made, just needs to be downloaded
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    #Posts to a path relative to docker container, allows for persistance of data, if container switches off the data stays, without this volume, this becomes a temp db 
    volumes:
      - postgres-db:/var/lib/postgresql/data
    #added this to fix race condition
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


#Called Globally
volumes:
  postgres-db: