version: '3'

services:
  api:
  #Looks for a dockerfile and starts the dockerfile
    build: .
    #HOST:CONTAINER, 8000 (my laptop,e.gd)  →  8000 (inside Docker container)
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=Password123
      - DATABASE_NAME=Fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=your_secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=300
    #Binding volume, binds current folder to folder in container, ro is read only, the container can't write to my computer i can write to the container
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    #Added to fix race condition
    depends_on:
      postgres:
        condition: service_healthy
    #depends_on:
     # - postgres

  #Uses Dns somehow? postgres ip, docker internal network?
  postgres:
  #Doesn't need dockerfile, it is from the sky, like dockerhub, it is already made, just needs to be downloaded
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: Password123
      POSTGRES_DB: Fastapi
    ports:
      - "5432:5432"
    #Posts to a path relative to docker container, allows for persistance of data, if container switches off the data stays, without this volume, this becomes a temp db 
    volumes:
      - postgres-db:/var/lib/postgresql/data
    #added this to fix race condition
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Fastapi"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s


#Called Globally
volumes:
  postgres-db: